apiVersion: v1 # 레플리케이션의 api 버전
kind: ReplicationController # 레플리케이션 컨트롤러 타입
metadata: # 기본 메타 정보
  name: kubia # 레플리케이션 명칭
spec: # 레플리케이션 스팩
  replicas: 2 # 레플리케이션이 관리하는 파트 숫자
  selector: # 파드 셀렉터
    app: kubia  # 파트 레이블 명칭
  template: # 새 파드에 사용할 템플릿
    metadata: # 새 파드에 적용할 메타 정보
      labels:
        app: kubia # 새 파드에 적용할 레이블 정보
    spec: # 새 파드에 적용할 스팩
      containers: # 새 파드에 적용할 컨테이너
        - name: kubia # 새 파드에 적용할 컨테이너 명칭
          image: luksa/kubia  # 새 파드에 적용할 컨테이너 이미지
          ports: # 새 파드에 적용할 포트 정보
            - containerPort: 8080 # 새 파드에 적용할 포트
