apiVersion: v1 # 파드 api 버전
kind: Pod # 타입
metadata: # 포드 메타 데이터 
  name: downward # 포트 명칭
spec: 
  containers: # 포드 컨테이너
  - name: main # 컨테이너 명칭
    image: busybox # 컨테이너에 사용할 이미지
    command: ["sleep", "9999999"] # 실행 시 적용할 명령어
    resources: # 리소스 정보
      requests: # 요청 리소스
        cpu: 15m # cpu
        memory: 100Ki # 메모리
    env: # 환경변수
    - name: POD_NAME # 포드명
      valueFrom:
        fieldRef:
          fieldPath: metadata.name # metadata.name을 참조[downward]
    - name: POD_NAMESPACE # 포드 네임 스페이스
      valueFrom:
        fieldRef:
          fieldPath: status.podIP # 실행 시 status에 있는 podIP를 참조
    - name: NODE_NAME # 노드 명칭
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName # 실행 시 spec.nodeName을 참조
    - name: SERVICE_ACCOUNT # 서비스 계정 정보
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName # 실행 시 spec.serviceAccountName을 참조
    - name: CONTAINER_CPU_REQUEST_MILLICORES # 
      valueFrom:
        resourceFieldRef: # 리소스 정보를 가져오고 싶을 경우 fieldRef가 아닌 resourceFieldRef를 사용
          resource: requests.cpu
          divisor: 1m
    - name: CONTAINER_MEMORY_REQUEST_KILLOBYTE
      valueFrom:
        resourceFieldRef:
          resource: requests.memory
          divisor: 1Ki

