apiVersion: networking.k8s.io/v1 # 서비스 api 버전
kind: Ingress # 서비스 타입
metadata: # 서비스 메타 정보
  name: kubia-ingress # 서비스 명칭
spec:
  rules: # 서비스 룰
  - host: kubia.example # 호스트 정보
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubia-nodeport
            port: 
              number: 80
