apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo
imagePullSecrets:
- name: my-dockerhub-secret
automountServiceAccountToken: true

---

apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  serviceAccountName: foo
  containers:
  - name: p0
    image: kim0lil/80700:v-1.0.0  

# bin/minikube.exe start --extra-config=apiserver.authorization-mode=RBAC
# GKE --no-enable-legacy-authorization