apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: foo
  name: service-reader
rules:
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["services"]

  #kubectl create clusterrolebinding culster-admin-binding --clusterrole=cluster-admin --user=kim0lil@co.kr