apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  labels:
    app: nfs
spec:
  containers:
  - image: centos:7
    name: nfs-server
    args: ["99999999"]
    command: ["/sbin/init","sleep"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: nfs-volume
      mountPath: /nfs
    ports:
    - containerPort: 111
    - containerPort: 1110
  volumes:
  - name: nfs-volume
    hostPath:
      path: /nfs

---

apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
  labels:
    app: nfs
spec:
  containers:
  - name: nfs-client
    image: centos:7
    args: ['99999999']
    command: ["/sbin/init","sleep"]
    securityContext:
      privileged: true