apiVersion: v1
kind: Pod
metadata:
  name: pod-volumes
  labels:
    app: node
spec:
  containers:
  - image: kim0lil/80700:v-3.0.0
    name: node
    volumeMounts:         # 마운트 할 볼륨 정보
    - name: host-volume   # 마운트 할 볼륨 명칭 등록
      mountPath: /host    # 마운트 할 경로 등록
  volumes:                # 볼륨 정보
  - name: host-volume     # 볼륨 명칭 등록
    hostPath:             # 호스트 경로 정보
      path: /host         # 호스트 경로 등록
      type: ""            # 타입을 강제하지 않음