apiVersion: v1
kind: Namespace
metadata:
  name: limit-cpu

---

apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-cpu
  namespace: limit-cpu
spec:
  limits:
  - default:          # 최초 값을 등록
      cpu: 2          # cpu 최소 치는 [2] 코어로 지정
    defaultRequest:   # 최대 확장 치를 등록
      cpu: 500m       # 최대 확장 코어는 [500m]
    type: Container

---

apiVersion: v1
kind: Pod
metadata:
  name: node
  namespace: limit-cpu
  labels:
    app: node
spec:
  containers:
  - name: node
    image: kim0lil/80700:v-1.0.0
    ports:
    - containerPort: 8080
