apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: namespace-rq
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: rq
    namespace: namespace-rq
  spec:
    hard:              # 하드웨어 리미트 등록
      pods: 2          # 파드의 최대 개수를 2로 지정
- apiVersion: v1     # 동일한 파드 3개 생성
  kind: Pod
  metadata:
    name: pod-rq-1
    namespace: namespace-rq
    labels:
      app: node
  spec:
    containers:
    - name: node
      image: kim0lil/80700:v-1.0.0
- apiVersion: v1
  kind: Pod
  metadata:
    name: pod-rq-2
    namespace: namespace-rq
    labels:
      app: node
  spec:
    containers:
    - name: node
      image: kim0lil/80700:v-1.0.0
- apiVersion: v1
  kind: Pod
  metadata:
    name: pod-rq-3
    namespace: namespace-rq
    labels:
      app: node
  spec:
    containers:
    - name: node
      image: kim0lil/80700:v-1.0.0