apiVersion: v1
kind: Namespace
metadata:
  name: limit-min-max

---

apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-min-max
  namespace: limit-min-max
spec:
  limits:
  - min:
      memory: 10Mi
    max:
      memory: 1Gi
    defaultRequest:
      memory: 100Mi
    type: Container

---

apiVersion: v1
kind: Pod
metadata:
  name: limit-pod-min
  namespace: limit-min-max
  labels:
    app: node
spec:
  containers:
  - name: node
    image: kim0lil/80700:v-1.0.0
    ports:
    - containerPort: 8080
    resources:          # 리소스 정보를 파드에 등록
      requests:         # 리소스 요청
        memory: 5Mi     # 최소 값(min)은 10Mi 이지만 5Mi로 요청


---

apiVersion: v1
kind: Pod
metadata:
  name: limit-pod-max
  namespace: limit-min-max
  labels:
    app: node
spec:
  containers:
  - name: node
    image: kim0lil/80700:v-1.0.0
    ports:
    - containerPort: 8080
    resources:          # 리소스 정보를 파드에 등록
      requests:         # 리소스 요청
        memory: 2Gi     # 최대 값(max)은 1Gi 이지만 2Gi로 요청