apiVersion: v1
kind: Pod
metadata:
  name: limited-pod
  namespace: limit
  annotations:
    memory.limit: limit-request-128Mi-limit-256Mi
  labels:
    app: node
spec:
  containers:
  - name: node
    image: kim0lil/80700:v-1.0.0
    ports:
    - containerPort: 8080