apiVersion: v1
kind: Pod
metadata:
  name: pod-volumes-dir
  labels:
    app: node
spec:
  containers:
  - image: kim0lil/80700:v-3.0.0
    name: node
    volumeMounts:
    - name: host-volume
      mountPath: /host
  volumes:
  - name: host-volume
    hostPath:
      path: /host
      type: Directory