apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-host-volume-claim
spec:
  storageClassName: standard # 저장소 클래스 타입을 기본으로 등록
  accessModes:               # PersistentVolume에 등록한 접근 권한 요청    
  - ReadWriteOnce            # 읽기/쓰기 모드로 요청
  resources:                 # 저장소에서 리소스를 요청
    requests:                # 요청 정보
      storage: 10Gi          # 10기가 저장소 요청
  selector:                  # 선택자 등록
    matchLabels:             # 레이블 선택
      type: host             # type=host 인 persistentVolume 선택