apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
spec:
  containers:
  - name: node
    image: kim0lil/80700:v-1.0.0
    env:
    - name: app_version            # 환경에 등록할 명칭
      valueFrom:                   # 값을 가져올 정보
        configMapKeyRef:           # 설정 맵 정보
          name: configmap          # 설정 맵 명칭
          key: application_version # 설정 맵의 등록 된 속성 값
