apiVersion: v1
kind: Pod
metadata:
  name: pod-with-downward
  labels:                       # 레이블 정보
    app: node
  annotations:                  # 어노테이션 정보
    app.version: 1.0.0
    app.status: normal
spec:
  containers:
  - name: app-node
    image: kim0lil/80700:v-1.0.0
    resources:                   # 리소스 요청을 등록
      limits:                    # 최대 정보
        storage: 1Gi             # 최대 저장소 정보
      requests:                  # 최대 요청 정보
        storage: 1Gi             # 최대 요청 저장소 정보