apiVersion: v1
kind: Pod
metadata:
  name: normal-pod
  labels:
    app: node
spec:
  containers:
  - image: kim0lil/80700:v-1.0.0
    name: normal-container

---

apiVersion: v1
kind: Pod
metadata:
  name: node-pid-pod
  labels:
    app: node
spec:
  hostPID: true      # 호스트간 프로세스 아이디 공유 가능
  hostIPC: true      # 호스트간 처리 공유 가능
  containers:
  - image: kim0lil/80700:v-1.0.0
    name: node-pid-container
