apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: view-pod-with-url-role
  rules:
  - nonResourceURLs: 
    - /api/v1/pods/*   # URL을 사용한 권한 인증
    verbs:
    - get
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: view-pod-with-url-rolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view-pod-with-url-role
  subjects:
  - kind: ServiceAccount
    name: sa-1
    namespace: ns-1

