apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      name: node-pod
      labels:
        app: node
    spec:
      containers:
      - image: kim0lil/80700:v-1.0.0
        name: node-pod-container

---

apiVersion: v1
kind: Service
metadata:
  name: node-8080-service
spec:
  type: NodePort
  selector: 
    app: node
  ports:
  - port: 8080           # 서비스를 노출할 포트
    nodePort: 30001      # 노드로 들어 오는 포트를 지정
    targetPort: 8080     # 파드로 전송할 포트를 지정