apiVersion: v1
kind: Pod
metadata:
  name: normal-pod
spec:
  containers:
  - image: alpine
    name: normal-container
    command: ["sleep"]
    args: ["999999999"]

---

apiVersion: v1
kind: Pod
metadata:
  name: node-port-pod
spec:
  hostNetwork: true
  containers:
  - image: alpine
    name: node-eth0-container
    command: ["sleep"]
    args: ["999999999"]