apiVersion: v1 # 서비스 api 버전
kind: Service # 서비스 타입
metadata: # 서비스 메타 정보
  name: kubia-svc-sa # 서비스 명칭
spec:
  ports: # 서비스 포트 정보
  - port: 80 # 서비스 포트 번호
    targetPort: 8080 # 포워딩 포트 번호
  - port: 443 # 서비스 포트 번호
    targetPort: 8443 # 포워딩 포트 번호
  selector: # 서비스 밸런싱 선택자
    app: kubia # 서비스 밸런싱 레이블