apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  annotations:           # 히스토리를 생성하기 위하여 어노테이션 레이블을 등록
    kubernetes.io/change-cause: application create version 1.0.0
spec:
  strategy: 
    type: RollingUpdate # 업데이트 타입을 롤링 업데이트(순차적 처리)로 등록
  minReadySeconds: 10
  replicas: 5
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: kim0lil/80700:v-1.0.0
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  type: ClusterIP
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 8080