apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: kim0lil.co.kr
    http:
      paths:
      - pathType: Prefix
        path: /v1
        backend:
          service:
            name: service-v1
            port:
              number: 8888
      - pathType: Prefix           # 룰 서비스를 추가 등록
        path: /v2
        backend:
          service:
            name: service-v2
            port:
              number: 9999