apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-v2
  template:
    metadata:
      labels:
        app: node-v2
    spec:
      containers:
      - name: node-v2
        image: kim0lil/80700:v-1.0.2
        ports:
        - containerPort: 8080
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: service-v2
spec:
  type: LoadBalancer
  selector:
    app: node-v2
  ports:
  - port: 9999
    targetPort: 8080
