apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: kim0lil/80700:v-1.0.0
        ports:
        - containerPort: 8080
          protocol: TCP