apiVersion: v1
kind: Service
metadata:
  name: env-service
spec:
  selector:
    app: env
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: env-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: env
  template:
    metadata:
      labels:
        app: env
    spec:
      containers:
      - name: env-cont
        image: kim0lil/80700:v-1.0.0
        ports:
        - containerPort: 8080