apiVersion: v1
kind: Endpoints
metadata:
  name: svc-endpoint
subsets:             # 아이피 셋을 구성
- addresses:         # 아이피 주소를 등록
  - ip: 172.17.0.3   # 셋 아이피를 등록
  - ip: 172.17.0.4   # 셋 아이피를 등록
  ports:             # 서비스 연결을 위한 포트
  - port: 8080       # 서비스 포트를 등록