apiVersion: v1
kind: Service
metadata:
  name: svc-log
spec:
  selector:
    app: app-log
  type: LoadBalancer
  ports:
  - name: app
    port: 8080
    targetPort: 8080
  - name: log
    port: 8090
    targetPort: 8090