apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-log
spec:
  storageClassName: host-dir-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: host