apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  labels:
    type: host
spec:
  storageClassName: host-dir-storage-class
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /host