apiVersion: v1 # 포드 api 버전
kind: Pod # 포드 타입
metadata: # 포트 메타 정보
  name: fortune-config-mode # 포드 명칭
spec: # 포드 스펙
  containers: # 컨테이너 정보
  - image: kim0lil/fortune # 컨테이너 이미지
    name:  html-generator # 이미지 명칭
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    volumeMounts: # 마운트 정보
    - name: html # 마운트 명칭(볼륨에 지정)
      mountPath: /var/htdocs # 마운트 경로
  - image: nginx:alpine # 컨테이너 이미지
    name: web-server
    volumeMounts: # 마운트 정보
    - name: html # 마운트 명칭
      mountPath: /usr/share/nginx/html # 마운트 경로
      readOnly: true # 읽기 전용 모드
    - name: config
      mountPath: /etc/nginx/conf.d/gzip.conf
      subPath: default.conf
      readOnly: true
    ports: # 포트 정보
    - containerPort: 80 # 오픈 포트
      protocol: TCP # TCP/UDP 여부
  volumes: # 볼륨 정보
  - name: html # 볼륨 명칭
    emptyDir: {} # 볼륨 타입
  - name: config
    configMap:
      name: fortune-config
      defaultMode: 0777