apiVersion: v1 # 파드의 api 버전
kind: Pod # 스팩 타입(파드)
metadata: # 기본 메타 정보
  name: kubia-liveness # 파드 명칭
spec: # 파드 스팩
  containers: # 컨테이너 스팩
    - image: luksa/kubia-unhealthy # 도커 이미지
      name: kubia-unhealthy # 컨테이너 이름
      livenessProbe: # 라이븐리스 브로브
        httpGet: # GET 요청
          path: / # 컨텍스트
          port: 8080 # 포트
        initialDelaySeconds: 15 # 딜레이 시간